### PR TITLE
Add license

### PR DESCRIPTION
**Pull request by smeets**
- BSD 2-clause with copyright to "Lund University and connect contributors"
 - Contributors are listed

### CODE REVIEW

**Comment by smeets** [comment]
@emenlu any thoughts on the copyright stuff?

**Comment by emenlu** [comment]
Yes, I'm not sure about the copyright. We could write Lund University and connect contributors. Why do you want to distinguish between contributors and authors?

**Comment by smeets** [comment]
It's a human who writes code but it could be an organisation that employs that code writer. I.e. people contribute but are not always the authors (from a copyright point of view). Does that make sense?

We could probably just mash them together have something like you suggested -- I think it's just a matter of technicality.

**Comment by smeets** [comment]
@emenlu I've updated the files; any comments?

**Comment by emenlu** [comment]
@smetz In this case contributors have copyright so I suggest that you change to "This file lists contributors". We could also add date of first contribution to the format. Then you could go back in history if you for some reason would like to do that.

I also think you should add Alex since he was involved in the project as a whole and not only the fronted development.

Remove the following from the CONTRIBUTORS file:
 
"# If a name is added to this file, consider adding"
 "# it to the AUTHORS file - either the name itself"

**Comment by smeets** [comment]
Nice catches! When did you guys start?

**Comment by emenlu** [comment]
Same day as you and Alex :-)

**Comment by smeets** [comment]
Hmm, around 5/11/15 or was it in october?

**Comment by smeets** [comment]
Format: `Given Family <email> <date>`

```
sorted by given name

Alexander Cobleigh <angellus.falsus@gmail.com> <2015-10-05>
Axel Smeets <murlocbrand@gmail.com> <2015-10-05>
Emelie Engström <emelie.engstrom@cs.lth.se> <2015-10-01>
Erik Andersson <eng10ea2@student.lu.se> <2016-09-05>
Kai Petersen <kaipetersen79@gmail.com> <2015-10-01>
Nauman Ali <nauman.ali@gmail.com> <2015-10-01>
Tim Borglund <tim.borglund@gmail.com> <2016-09-05>
Jamie Caprani <ja8674ca-s@student.lu.se> <2016-10-28>

sorted by join date -- tie break with given

Emelie Engström <emelie.engstrom@cs.lth.se> <2015-10-01>
Kai Petersen <kaipetersen79@gmail.com> <2015-10-01>
Nauman Ali <nauman.ali@gmail.com> <2015-10-01>
Alexander Cobleigh <angellus.falsus@gmail.com> <2015-10-05>
Axel Smeets <murlocbrand@gmail.com> <2015-10-05>
Erik Andersson <eng10ea2@student.lu.se> <2016-09-05>
Tim Borglund <tim.borglund@gmail.com> <2016-09-05>
Jamie Caprani <ja8674ca-s@student.lu.se> <2016-10-28>
```

I think it makes more sense to sort by name, any thoughts?

**Comment by emenlu** [comment]
I agree

**Comment by smeets** [comment]
Ok, then we're live!

**Comment by smeets** [comment]
[Set a LICENSE file](https://trello.com/c/Z4lUFvau/1-set-a-license-file)

**Pull request merged**
