### PR TITLE
added filter for date,contact,entrytype

### PR DESCRIPTION
**Pull request by Drullan**
Fixes #44

### CODE REVIEW

**Comment by smeets** [comment]
Ait this looks nice.

What is the difference between `xss` and `xss2`? Do I need to merge both this and #44 ?

**Comment by smeets** [comment]
[#44 New filter utility class for xss](https://trello.com/c/894uYrXZ/83-44-new-filter-utility-class-for-xss)

**Comment by Drullan** [comment]
no only merge this one. I got some problem with pushing to xss so I had to make a new branch. There is no difference except that I added filter for the mentioned types aswell.

**Comment by smeets** [comment]
Then I think you can go ahead and merge!

**Pull request merged**
