### PR TITLE
Acceptinvite

### PR DESCRIPTION
**Pull request by Drullan**
I think I used auto indent and that's probably why the entire document is highlighted in Collection.
I added POST("/{id}/reject",.. since it was missing and modified the existing POST("/{id}/accept",
and POST("/{id}/invite". Also made the helper function  private void handleInvitation near the end of the document. 
I added a mail template for accepting invites. 
For getting it to work I needed to keep track of who invited who, therefor I added a relation "inviter" which points from the person who invited to the person who got invited. I keep track of which collection the user got invited to by adding a property to the relation with the collection id. 
Potential bugs:
I noticed that you can invite people who are already in the collection and they would then receive an invite to a collection they are member of. 
I also noticed that stats won't return how many members there are in a collection if there are no entries in that collection. This is probably not a major problem since it makes no sense to have empty collections with lots of members but it is a bit weird behaviour.

### CODE REVIEW

**Review by Timbozand — COMMENTED** [review]
I checked out the code and the indentation seems to be correct. 

I noticed that some of the test cases did not go through. Strangely, I noticed that this seems to also be true for the master branch. @smeetz do you know if this problem has been around before?

**Comment by Timbozand** [comment]
I talked to @smeetz IRL and he found the bug (it was related to the XSS filter) so now the tests on the master branch pass.

**Review by Timbozand — APPROVED** [review]

**Review by Timbozand — CHANGES_REQUESTED** [review]
Maybe we should change so that you can't invite people who is already part of the collection? Doesn't seem like that big of a problem but still.

**Comment by Drullan** [comment]
We now check if the user to be invited isn't already member of the collection before we send the invite.

**Review by smeets — CHANGES_REQUESTED** [review]
Merge the two queries (268-280)

**Review by Timbozand — APPROVED** [review]

**Review by smeets — APPROVED** [review]

**Comment by smeets** [comment]
[When a user you invited to a collection accepts/rejects it, you should get an email](https://trello.com/c/vSLRaMPL/101-when-a-user-you-invited-to-a-collection-accepts-rejects-it-you-should-get-an-email)

**Comment by smeets** [comment]
I created new branch (i66) and merged this into master. All tests are fine and notifications are at least sent. We will probably have to keep an eye open for any leftover bugs. In the future, just undo the code formatting, otherwise: :hear_no_evil:  :gun:

**Pull request closed without merging**
